id: A4F4F783B
title: The Means for Accomplishment called the Blazing Wheel
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:52:56.693342
  last_modified_at: 2022-03-01 04:52:56.693348
